title: The Sales Rebellion
url: "https://www.thesalesrebellion.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-menus
  - jekyll-redirect-from
