title: The Sales Rebellion
url: "https://www.thesalesrebellion.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "posts"
    values:
      permalink: '/blog/:year/:month/:day/:title/'
      layout: post
      section: blog-post inverse
  -
    scope:
      path: "_old"
    values:
      published: false
pagination:
  enabled: false
  per_page: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 3
    after: 3

plugins:
  - jekyll-menus
  - jekyll-redirect-from
  - jekyll-paginate-v2
