---
name: HTMLProofer
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  checklinks:
    name: HTMLProofer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        id: bundler-cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: lemonarc/jekyll-action@1.0.0
      - name: HTMLProofer
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./_site"
          arguments: --disable-external
      - name: HTMLProofer external links
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./_site"
          arguments: --external-only --http-status-ignore "999" --url-ignore "/(facebook.com)/"
        continue-on-error: true
